server:
  port: 8082

spring:
  application:
    name: ticketing-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ticketing_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: guest
    password: guest
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-here-must-be-very-long-for-security}

vnpay:
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    # ← Trỏ thẳng về backend callback qua ngrok
  return-url: https://unrodded-jayme-unappreciably.ngrok-free.dev/api/v1/payments/vnpay/callback
    # Frontend URL dùng riêng sau này
  frontend-url: http://localhost:5173/payment/result
  tmn-code: ${VNPAY_TMN_CODE:MLD6BFSF}
  hash-secret: ${VNPAY_HASH_SECRET:C1LB8AXS24QDVIWQ06LDY0KOPLHWTZUI}

app:
  rabbitmq:
    exchange: ticket.exchange
    queue:
      booking-confirmed: booking.confirmed.queue
      booking-cancelled: booking.cancelled.queue
    routing-key:
      booking-confirmed: booking.confirmed
      booking-cancelled: booking.cancelled
  booking:
    hold-duration-minutes: 10
  football-api:
    url: https://api.football-data.org/v4
    api-key: ${FOOTBALL_API_KEY:}
    competition: PL    # Premier League
  gemini:
    api-key: ${GROQ_API_KEY:}
  newsapi:
    api-key: ${NEWS_API_KEY:}