server:
  port: ${PORT:8082}

spring:
  application:
    name: ticketing-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}        # ← đổi từ DB_URL
    username: ${SPRING_DATASOURCE_USERNAME}  # ← đổi từ DB_USERNAME
    password: ${SPRING_DATASOURCE_PASSWORD}  # ← đổi từ DB_PASSWORD

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    addresses: ${SPRING_RABBITMQ_URI}

  data:
    redis:
      url: ${SPRING_DATA_REDIS_URL}

jwt:
  secret: ${JWT_SECRET}

vnpay:
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: ${VNPAY_RETURN_URL}
  frontend-url: ${FRONTEND_URL}
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET}

app:
  rabbitmq:
    exchange: ticket.exchange
    queue:
      booking-confirmed: booking.confirmed.queue
      booking-cancelled: booking.cancelled.queue
    routing-key:
      booking-confirmed: booking.confirmed
      booking-cancelled: booking.cancelled

  booking:
    hold-duration-minutes: 10

  football-api:
    url: https://api.football-data.org/v4
    api-key: ${FOOTBALL_API_KEY}
    competition: PL

  gemini:
    api-key: ${GROQ_API_KEY}

  newsapi:
    api-key: ${NEWS_API_KEY}